modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/MC-Backports/spring_to_life/issues"
license = "GPL-3.0"

[[mods]]
modId = "spring_to_life"
version = "${version}"
displayName = "Spring to Life"
authors = "LarsenR"
description = '''
This mod ports some features from the "Spring to Life" feature drop (Minecraft 1.21.5) back to 1.21.1
'''
logoFile = "assets/spring_to_life/logo.png"

[[dependencies.spring_to_life]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spring_to_life]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "spring_to_life.mixins.json"

[[mixins]]
config = "spring_to_life_neoforge.mixins.json"
